### ISSUE TITLE
Error on Kodi 20

### ISSUE THREAD

**Issue by freespirit83xyz** [hjgode/plugin.video.xtreamclient2#1]
I've tested this add-on on Kodi 20. Login and browsing for series and movies works well and search works very well too, but there is an issue when I try to list episodes of a serie. This is the log error:

```
2023-02-11 15:40:27.858 T:24855    info <general>: [plugin.video.xtreamclient:live_archive_xbmc] b'###router called with: {\'action\': \'list_episodes_in_season\', \'season_number\': \'1\', \'serie_id\': \'3895\', \'serie_name\': "C\'era una volta... Pollon"}'
2023-02-11 15:40:27.858 T:24855    info <general>: [plugin.video.xtreamclient:live_archive_xbmc] b'router() list_episodes_in_season...'
2023-02-11 15:40:27.858 T:24855    info <general>: [plugin.video.xtreamclient] ### list_episodes_in_season
2023-02-11 15:40:27.858 T:24855    info <general>: [plugin.video.xtreamclient2] get_settings...
2023-02-11 15:40:27.859 T:24855    info <general>: [plugin.video.xtreamclient2] get_settings addon=/storage/.kodi/addons/plugin.video.xtreamclient2/
2023-02-11 15:40:27.860 T:24855    info <general>: [plugin.video.xtreamclient2] get_settings...
2023-02-11 15:40:27.860 T:24855    info <general>: [plugin.video.xtreamclient2] get_settings addon=/storage/.kodi/addons/plugin.video.xtreamclient2/
2023-02-11 15:40:28.555 T:24855    info <general>: [plugin.video.xtreamclient] season_number: 1
2023-02-11 15:40:28.555 T:24855    info <general>: [plugin.video.xtreamclient] episodes is a dict!
2023-02-11 15:40:28.555 T:24855    info <general>: [plugin.video.xtreamclient] looking for video in episodes[season_number]...
2023-02-11 15:40:28.555 T:24855    info <general>: [plugin.video.xtreamclient] **** list_episodes_in_season(), direct_source=
2023-02-11 15:40:28.559 T:24855   error <general>: NEWADDON Unknown Video Info Key "video"
2023-02-11 15:40:28.559 T:24855 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-02-11 15:40:28.626 T:24855   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'cover_big'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.xtreamclient2/main.py", line 269, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.xtreamclient2/main.py", line 229, in router
                                                       list_episodes_in_season(None, params['season_number'], params['serie_name'], params['serie_id'])
                                                     File "/storage/.kodi/addons/plugin.video.xtreamclient2/series_xtream.py", line 417, in list_episodes_in_season
                                                       list_item.setArt({'thumb': video['info']['movie_image'], 'icon': video['info']['movie_image'], 'fanart': video['info']['cover_big']})
                                                                                                                                                                ~~~~~~~~~~~~~^^^^^^^^^^^^^
                                                   KeyError: 'cover_big'
                                                   -->End of Python script error report<--
                                                   
2023-02-11 15:40:28.927 T:24854   error <general>: GetDirectory - Error getting plugin://plugin.video.xtreamclient2/?action=list_episodes_in_season&season_number=1&serie_id=3895&serie_name=C%27era%20una%20volta...%20Pollon
2023-02-11 15:40:28.943 T:23528   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.xtreamclient2/?action=list_episodes_in_season&season_number=1&serie_id=3895&serie_name=C%27era%20una%20volta...%20Pollon) failed
2023-02-11 15:40:31.165 T:24633   error <general>: CCurlFile::Stat - <http://194.152.45.37:8080/images/79b667462c483c9da62a2d33aa8c96f8.jpg> Failed: Timeout was reached(28)
```

**Comment by freespirit83xyz** [comment]
I do a path and I can go on but there is another error when I try to start an episode.

`2023-02-11 20:02:08.478 T:5487    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'video'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.xtreamclient2/main.py", line 271, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.xtreamclient2/main.py", line 253, in router
                                                       play_video(params['video'])
                                                                  ~~~~~~^^^^^^^^^
                                                   KeyError: 'video'
                                                   -->End of Python script error report<--`

There is no key "video", the only key in params is "action"

**Comment by hjgode** [comment]
I am sorry, but the plugin is for Kodi 18 and 19, not for Kodi 20. Too many changes and I do not have a valid test environ for this.
